<a href="https://colab.research.google.com/github/sammywenthikingwithshroomtrolls/Flash-Flood-Data-Analysis-of-August-2024/blob/main/Create_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# creating numpy array/ n-dimensional array

In [ ]:
import numpy as np

In [2]:
arr1=np.array([3,4,5,6,7,8,8])
arr1

array([3, 4, 5, 6, 7, 8, 8])

**to check data type of the array type(arr1)**





In [3]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,6,7,7,8]])
arr2

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 6, 7, 7, 8]])

In array, it's like matrix, so elements of two list's value needs to be equal. for example 7 value in 1st list, then needs to be 7 value in 2nd list

In [8]:
arr3=np.zeros((4,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

so, it's mostly like the straight line where we are inputing the values like arr2, arr3=etc etc, there the value can be considered as **vector**,
and when we print it, then we can call it '**Matrix**'

In [10]:
arr4=np.ones((10,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

1st value in the bracket is row, 2nd is coloumn

In [11]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Notice: it's **arange**, not arrange. There is no function named arrange in NumPy. The function you meant to use is arange, **which returns evenly spaced values within a given interval.**

In [20]:
arr6=np.arange(9-20)
arr6

array([], dtype=int64)

In [21]:
arr7=np.arange(9,20)
arr7

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
arr8=np.linspace(10,25,10)
arr8

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        , 21.66666667, 23.33333333, 25.        ])

here, first value in bracket is 1st range, 2nd one is last value of range, 10 is the number of elements I want within this range. So, this means the value of the elements are float in any array



In [23]:
arr8=arr7.copy()
arr8

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

copy function copies the value of other array, I will ask it to copy
